<?php

/**
 * Implements hook_help
 *
 */
function cog_zoho_crm_help($path, $arg) {
  switch ($path) {
    case "admin/help#cog_zoho_crm":
      return t('Integrates with Zoho CRM');
      break;
  }
}

/**
 * Implements hook_menu()
 *
 */
function cog_zoho_crm_menu() {
  $items = array();
  
  $items['admin/commerce/cog_zoho_crm_import'] = array(
    'title' => 'Import Courses and Workshops',
    'description' => 'Import new and updated data from Zoho CRM',
    'page callback' => 'cog_zoho_crm_import',
    'access callback' => 'admin_landing_page_access',
    'access arguments' => array('admin/commerce'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Page callback: Zoho CRM Import
 *
 * @see cog_zoho_crm_menu()
 */
function cog_zoho_crm_import() {
  module_load_include('inc','cog_zoho_crm','cog_zoho_crm_api');

  $params['authtoken'] = AUTHTOKEN;
  $params['scope'] = SCOPE;
  $params['selectColumns'] = 'products(Product Name,Product Code,Unit Price,Location)';
  $params['fromIndex'] = 1;
  $params['toIndex'] = 5;
  $params['newFormat'] = 2;
  
  dpm($params);
  
  $output = t('Here it is...');
  return $output;
}

